[workspace]
resolver = "2"
members = [
    "crates/tokmd",
    "crates/tokmd-config",
    "crates/tokmd-format",
    "crates/tokmd-model",
    "crates/tokmd-scan",
    "crates/tokmd-tokeignore",
    "crates/tokmd-types",
    "fuzz",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
