[workspace]
resolver = "2"
members = [
    "crates/tokmd",
    "crates/tokmd-analysis",
    "crates/tokmd-analysis-format",
    "crates/tokmd-analysis-types",
    "crates/tokmd-config",
    "crates/tokmd-core",
    "crates/tokmd-content",
    "crates/tokmd-format",
    "crates/tokmd-fun",
    "crates/tokmd-git",
    "crates/tokmd-model",
    "crates/tokmd-scan",
    "crates/tokmd-tokeignore",
    "crates/tokmd-types",
    "crates/tokmd-walk",
    "fuzz",
]
default-members = [
    "crates/tokmd",
    "crates/tokmd-analysis",
    "crates/tokmd-analysis-format",
    "crates/tokmd-analysis-types",
    "crates/tokmd-config",
    "crates/tokmd-core",
    "crates/tokmd-content",
    "crates/tokmd-format",
    "crates/tokmd-fun",
    "crates/tokmd-git",
    "crates/tokmd-model",
    "crates/tokmd-scan",
    "crates/tokmd-tokeignore",
    "crates/tokmd-types",
    "crates/tokmd-walk",
]

[workspace.package]
version = "1.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/EffortlessMetrics/tokmd"
repository = "https://github.com/EffortlessMetrics/tokmd"
authors = ["Steven Zimmerman <git@effortlesssteven.com>"]

[profile.release]
lto = true
codegen-units = 1
strip = true
