# Created with WinGet Manifest Creation Tool
# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: EffortlessMetrics.tokmd
PackageVersion: 1.6.3
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
  - tokmd
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/EffortlessMetrics/tokmd/releases/download/v1.6.3/tokmd-windows-amd64.exe
    InstallerSha256: 0842617376c57d5fcc5a8fb40395510011b998ae1fb32122263e4264cb35c5b1
    PortableCommandAlias: tokmd
ManifestType: installer
ManifestVersion: 1.6.0
