# Created with WinGet Manifest Creation Tool
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: EffortlessMetrics.tokmd
PackageVersion: 1.3.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
