[package]
name = "tokmd-scan"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokei = { version = "14.0.0", default-features = false }
tokmd-config = { path = "../tokmd-config" }
